name = "Quick Pixels"
license = "Apache-2.0"
licenselink = "https://github.com/toughpixels/quick-pixels/blob/main/LICENSE"
description = "Simple theme focused on an easy admin experience using Netlify CMS."
homepage = "https://github.com/toughpixels/quick-pixels"
tags = ["blog" ]
features = ["blog"]
min_version = "0.41.0"

[author]
  name = "Tough Pixels"
  homepage = "https://toughpixels.com"
