languageCode = "en-us"
theme = ["quick-pixels", "base"]
title = ""
baseURL = "https://example.com"

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
    languageName = "English"
    weight = 1
    contentDir = 'content/en'


[taxonomies]
  category = 'categories'
  tag = 'tags'


[params]
  description = ""
  homeLinkText = "Home"
  imageSizes = "736 288"
  imageFormats = "webp jpg"
  
  themeVars1 = "--background_color: #fafafa;\n--action_color: #1b6ea5;\n--accent_color: #860059;\n--text_color: #202020;\n--font_family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;"

themeVars2 = "--alt_background_color: #fbf8f2;\n--alt_action_color: var(--action_color);\n--alt_accent_color: var(--accent_color);\n--alt_text_color: var(--text_color);\n--alt_border_color: #6e0269;\n--default_font_size: 1.5rem;\n--default_line_height:1.6; \n--header_font_family: var(--font_family);"

themeVars3 = "--section_y_padding: 5rem;\n--section_y_padding_mobile: 2rem;\n--odd_numbered_sections_background_color: #eee;\n--navLinks_size: 2rem;\n--home_navLink_size: var(--navLinks_size);\n--leadText_size: 2.5rem;\n--container_width: 768px;\n--container_x_padding: 1rem;\n--aside_label_display: block;\n--aside_left_margin: 3rem;"

themeVars4 = "--h1_size: 4rem;\n--h2_size: 3.5rem;\n--h3_size: 3rem;\n--h4_size: 2.5rem;\n--h5_size: 2rem;\n--h6_size: 1.5rem;\n--header_size_mobile_reduction: 1.5;\n--h1_weight: 400;\n--h2_weight: 700;\n--h3_weight: 400;\n--h4_weight: 700;\n--h5_weight: 400;\n--h6_weight: 700;\n--h1_line_height: 1.1;\n--h2_line_height: 1.2;\n--h3_line_height: 1.3;\n--h4_line_height: 1.4;\n--h5_line_height: 1.5;\n--h6_line_height: 1.6;"


[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true